custom_data = {
    "location" :{
        "Munich": 0,
        "Berlin": 1,
        "Frankfurt": 2,
    },
    "item_definition" : {
            1001: {"name": "Melon", "image": "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/237/grapes_1f347.png"},
            1002: {"name": "Watermelon", "image": "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/melon_1f348.png"},
            1003: {"name": "Tangerine", "image": "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/watermelon_1f349.png"},
            1004: {"name": "Lemon", "image": "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/lemon_1f34b.png"},
            1005: {"name": "Banana", "image": "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/banana_1f34c.png"},
            1006: {"name": "Pineapple", "image": "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/pineapple_1f34d.png"},
            1007: {"name": "Mango",  "image": "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/mango_1f96d.png"},
            1008: {"name": "Red Apple",  "image":   "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/red-apple_1f34e.png"},
            1009: {"name": "Green Apple",  "image": "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/237/green-apple_1f34f.png"},
            1010: {"name": "Pear",  "image": ""},
            1011: {"name": "Peach",  "image": ""},
            1012: {"name": "Cherries",  "image": ""},
            1013: {"name": "Strawberry",  "image": ""},
            1014: {"name": "Kiwi Fruit",  "image": ""},
            1015: {"name": "Tomato",  "image": ""},
            1016: {"name": "Coconut",  "image": ""},
            1017: {"name": "Avocado",  "image": ""},
            1018: {"name": "Eggplant",  "image": ""},
            1019: {"name": "Potato",  "image": ""},
            1020: {"name": "Carrot",  "image": ""},
            1021: {"name": "Ear of Corn",  "image": ""},
            1022: {"name": "Hot Pepper",  "image": ""},
            1023: {"name": "Cucumber",  "image": ""},
            1024: {"name": "Leafy Green",  "image": ""},
            1025: {"name": "Broccoli",  "image": ""},
            1026: {"name": "Garlic",  "image": ""},
            1027: {"name": "Onion",  "image": ""},
            1028: {"name": "Mushroom",  "image": ""},
            1029: {"name": "Peanuts",  "image": ""},
            1030: {"name": "Chestnut",  "image": ""},
            1031: {"name": "Butter",  "image": ""},
            1032: {"name": "Salt",  "image": ""},
            1033: {"name": "Canned Food",  "image": ""},
            1034: {"name": "Chocolate Bar",  "image": ""},
            1035: {"name": "Candy",  "image": ""},
            1036: {"name": "Lollipop",  "Descripition": "" },
            1037: {"name": "Custard",  "Descripition": "" },
            1038: {"name": "Honey",  "Descripition": "" }
    },
    "last_item_id": 1038,
    "transactions": {
        0: {"name": "aaa", "date": "2020/20/12", "location": "munich", "items": [ {"item": 1001, "count":2} ]}
    },
    "last_transaction_id": 0

}